# Generated by Django 3.1.3 on 2020-11-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Directories',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('directory(in development)', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='simple_directory.directory(in development)')),
            ],
        ),
        migrations.AddField(
            model_name='directory(in development)',
            name='directory_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='simple_directory.directorybase'),
        ),
        migrations.AlterUniqueTogether(
            name='directory(in development)',
            unique_together={('version', 'directory_base')},
        ),
    ]
