# Generated by Django 3.1.3 on 2020-11-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory(in development)',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterUniqueTogether(
            name='directoryitem',
            unique_together={('directory(in development)', 'code', 'value')},
        ),
    ]
