# Generated by Django 3.1.3 on 2020-11-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0002_auto_20201130_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directoryitem',
            unique_together={('code', 'value')},
        ),
    ]
