# Generated by Django 3.1.3 on 2020-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0003_auto_20201201_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryitem',
            name='directory(in development)',
        ),
        migrations.AddField(
            model_name='directoryitem',
            name='directories',
            field=models.ManyToManyField(related_name='related_items', to='simple_directory.Directory'),
        ),
    ]
