# Generated by Django 3.1.3 on 2020-11-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0004_auto_20201201_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory(in development)',
            name='related_items',
            field=models.ManyToManyField(to='simple_directory.DirectoryItem'),
        ),
        migrations.AlterField(
            model_name='directoryitem',
            name='directories',
            field=models.ManyToManyField(to='simple_directory.Directory'),
        ),
    ]
