# Generated by Django 3.1.3 on 2020-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0005_auto_20201201_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryitem',
            name='directories',
            field=models.ManyToManyField(blank=True, to='simple_directory.Directory'),
        ),
    ]
