# Generated by Django 3.1.3 on 2020-11-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0006_auto_20201201_0211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory(in development)',
            unique_together={('version', 'directory_base'), ('start_date', 'version')},
        ),
    ]
