# Generated by Django 3.1.3 on 2020-11-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_directory', '0007_auto_20201201_0357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory(in development)',
            unique_together={('start_date', 'directory_base'), ('version', 'directory_base')},
        ),
    ]
